# Generated by Django 3.1.6 on 2021-02-14 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estoque', models.IntegerField()),
                ('estoqueTerceiros', models.IntegerField()),
                ('estoqueProducao', models.IntegerField()),
                ('estoqueAvariados', models.IntegerField()),
                ('dataInventario', models.DateTimeField()),
                ('prod', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='produto.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Armazenamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enderecos', models.ManyToManyField(to='estoque.Endereco')),
                ('produtos', models.ManyToManyField(to='produto.Produto')),
            ],
        ),
    ]
