# Generated by Django 3.1.6 on 2021-02-14 12:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('fullName', models.CharField(blank=True, max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('mobile', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('address_c', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=15)),
                ('taxRefund', models.CharField(blank=True, max_length=1)),
                ('incoterm', models.CharField(blank=True, max_length=40)),
                ('paymentTerm', models.CharField(blank=True, max_length=200)),
                ('bankName', models.CharField(blank=True, max_length=200)),
                ('bankAddress', models.CharField(blank=True, max_length=200)),
                ('bankAccount', models.CharField(blank=True, max_length=50)),
                ('bankIban', models.CharField(blank=True, max_length=50)),
                ('bankSwift', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
