# Generated by Django 3.1.6 on 2021-02-14 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cidade', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Linhas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Linha',
                'verbose_name_plural': 'Linhas',
            },
        ),
        migrations.CreateModel(
            name='Tabelas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('status', models.BooleanField()),
            ],
            options={
                'verbose_name': 'Tabela',
                'verbose_name_plural': 'Tabelas',
            },
        ),
        migrations.CreateModel(
            name='Representante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeFantasia', models.CharField(blank=True, max_length=100)),
                ('razaoSocial', models.CharField(blank=True, max_length=100)),
                ('responsavel', models.CharField(blank=True, max_length=100)),
                ('cpfCnpj', models.CharField(blank=True, max_length=30)),
                ('InscricaoEstadual', models.CharField(blank=True, max_length=30)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('celular', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
                ('emailNfe', models.CharField(blank=True, max_length=100)),
                ('emailFinanceiro', models.CharField(blank=True, max_length=100)),
                ('dataCadatro', models.DateTimeField(default=django.utils.timezone.now)),
                ('endereco', models.CharField(blank=True, max_length=100)),
                ('numero', models.CharField(blank=True, max_length=100)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(blank=True, max_length=2)),
                ('cep', models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MG', 'Minas Gerais'), ('MS', 'Mato Grosso do Sul'), ('MT', 'Mato Grosso'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PI', 'Piauí'), ('PE', 'Pernambuco'), ('PR', 'Paraná'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('RS', 'Rio Grande do Sul'), ('SC', 'Santa Catarina'), ('SE', 'Sergipe'), ('SP', 'São Paulo'), ('TO', 'Tocantins')], default='SP', max_length=10)),
                ('cidade', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cidade.cidades')),
                ('linha', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='representante.linhas')),
                ('tabela', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='representante.tabelas')),
            ],
        ),
    ]
