# Generated by Django 3.1.6 on 2021-02-14 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fornecedor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Divisao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ncm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('descricao', models.TextField()),
                ('ii', models.CharField(max_length=10)),
                ('ipi', models.CharField(max_length=10)),
                ('pis', models.CharField(max_length=10)),
                ('cofins', models.CharField(max_length=10)),
                ('icms', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('codigo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20)),
                ('codigoFornecedor', models.CharField(max_length=50)),
                ('ean', models.CharField(max_length=15)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('foto', models.ImageField(blank=True, upload_to='fotos/%Y/%m/d')),
                ('origem', models.CharField(choices=[('0', 'Nacional, exceto as indicadas nos códigos 3, 4, 5 e 8'), ('1', 'Estrangeira - Importação direta, exceto a indicada no código 6'), ('2', 'Estrangeira - Adquirida no mercado interno, exceto a indicada no código 7'), ('3', 'Nacional, mercadoria ou bem com Conteúdo de Importação superior a 40% (quarenta por cento) e inferior ou igual a 70% (setenta por cento)'), ('4', 'Nacional, cuja produção tenha sido feita em conformidade com os processos produtivos básicos de que tratam o Decreto-Lei no 288/67, e as Leis nos 8.248/91, 8.387/91, 10.176/01 e 11.484/07'), ('5', 'Nacional, mercadoria ou bem com Conteúdo de Importação inferior ou igual a 40% (quarenta por cento)'), ('6', 'Estrangeira - Importação direta, sem similar nacional, constante em lista de Resolução CAMEX e gás natural'), ('7', 'Estrangeira - Adquirida no mercado interno, sem similar nacional, constante em lista de Resolução CAMEX e gás natural'), ('8', 'Nacional, mercadoria ou bem com Conteúdo de Importação superior a 70% (setenta por cento)')], default=0, max_length=2)),
                ('classificacao', models.CharField(choices=[('0', 'Fabricação Própria'), ('1', 'Revenda'), ('2', 'Representação'), ('3', 'Produto Importado'), ('4', 'Mercadoria Consignada'), ('5', 'Revenda (Não Mantém Estoque)'), ('6', 'Fabricação Própria  (Não Mantém Estoque)')], default='0', max_length=2)),
                ('sped', models.CharField(choices=[('00', 'Mercadoria para Revenda'), ('01', 'Matéria-Prima'), ('02', 'Embalagem'), ('03', 'Produto em Processo'), ('04', 'Produto Acabado'), ('05', 'Subproduto'), ('06', 'Produto Intermediário'), ('07', 'Material de Uso e Consumo'), ('08', 'Ativo Imobilizado'), ('09', 'Serviços'), ('10', 'Outros insumos'), ('99', 'Outras')], default='00', max_length=2)),
                ('status', models.CharField(choices=[('0', 'INATIVO'), ('1', 'ATIVO'), ('2', 'NÃO COMPRAR'), ('3', 'DELETADO')], default='1', max_length=2)),
                ('dataCadatro', models.DateTimeField(default=django.utils.timezone.now)),
                ('fci', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('impostos', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('despesasImportacao', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valorFob', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valorDollar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('despesasOperacionais', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('dataCompra', models.DateTimeField()),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.categoria')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.departamento')),
                ('divisao', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.divisao')),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='fornecedor.fornecedor')),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.marca')),
                ('ncm', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.ncm')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='produto.tipo')),
            ],
        ),
    ]
